### ISSUE TITLE
Initial Branding

### ISSUE THREAD

**Issue by Nikro** [help2022-ukr/help2022#1]
Here's what we need:

- [x] SVG logo - should be elegant and simple.
- [x] 3-5 images for login (big size) - something related to Ukraine identity.
- more things to come..

**Comment by Nikro** [comment]
![image](https://user-images.githubusercontent.com/1063223/155642293-5e561e06-e1a8-4a44-b550-7628f6169acc.png)

**Comment by afinika** [comment]
![1618138263Ukraine-heart-shape-flag](https://user-images.githubusercontent.com/21144779/155648023-890f0c5c-f447-4892-9695-3390324ba27e.svg)

**Comment by afinika** [comment]
![tim-mossholder-bo3SHP58C3g-unsplash](https://user-images.githubusercontent.com/21144779/155648780-d068f602-928c-4ada-bb50-95a71fe94b46.jpg)
![tim-mossholder-epBIrtdg2Hk-unsplash](https://user-images.githubusercontent.com/21144779/155648795-6c4a5b89-9dce-4efc-9b6a-b28c06511f5a.jpg)
![tim-mossholder-zs-PAgqgenQ-unsplash](https://user-images.githubusercontent.com/21144779/155648796-3d8e2fd8-0191-4827-9b4d-8bc75fa15b0b.jpg)
![ian-dooley-DuBNA1QMpPA-unsplash](https://user-images.githubusercontent.com/21144779/155648835-1e3b3f34-d16a-4277-b819-681d0c7b302f.jpg)
![kelly-sikkema-4le7k9XVYjE-unsplash](https://user-images.githubusercontent.com/21144779/155648842-138220b7-2b30-4762-b3d9-86df88d2bcd9.jpg)

**Comment by Nikro** [comment]
![Screenshot from 2022-02-25 17-43-51](https://user-images.githubusercontent.com/1063223/155754708-0ec8033d-25d4-47c5-ab09-1d33ea31c1bc.png)
