### ISSUE TITLE
Content

### ISSUE THREAD

**Issue by Nikro** [help2022-ukr/help2022#13]
The homepage will be a textual page + with some links explaining the basics.

TODO
- [x] homepage for anonymous users 
- [x] about us page
- [x] host registration page
- [x] host thank you page
- [x] refugee filter page

**Comment by afinika** [comment]
copy https://docs.google.com/document/d/12mkHjcxsRtPKkVLs4u2lLEI09q6-bnoFTb0joSZehRQ/edit?usp=sharing

**Comment by Nikro** [comment]
Done homepage for anonymous - need to do redirect for logged-in.

**Comment by Nikro** [comment]
@afinika - I need some stuff from you!

1. Homepage - what images you want to add? Note that it should be something small / maybe all the neighboring flags around ukraine, or something - because it will take a lot of space on the mobile - right now it already takes almost all the space on mobile. Maybe some contact information??

2. About page - we need to fill in the about page:
- What is the project about
- State that it's done by international volunteers - maybe say who we are to gain trust of NGOs or maybe just to enumarate coutnries
- Do you want to state a road-map of our tool?
- Contacts?
- What do we need in terms of volunteers TECH and non-TECH? We def. need translators to Hungarian, Polish, etc.

3. I need the information that will be listed on the RIGHT SIDE of the submission of the Host Location - similar to what these guys have:

![Screenshot from 2022-02-26 13-33-30](https://user-images.githubusercontent.com/1063223/155843316-39c77859-4e53-4059-ab09-8d7419bcd8bd.png)

Upcoming: https://docs.google.com/document/d/10jA1Wj-Eq6IKyLU_QWHMxYKlA7oLcmvv8mYOb_F3lZI/edit
We need a guidance for every line specified here.

**Comment by afinika** [comment]
@Nikro the landing page updated with more content, see the doc.

**Comment by afinika** [comment]
all content is done, for now, will create more when needed.
