### ISSUE TITLE
problems assesment

### ISSUE THREAD

**Issue by afinika** [help2022-ukr/help2022#21]
- [x] [define the refugee journey ](https://miro.com/welcomeonboard/Mk1pdXBzUXlEaHBHWGtNNU9XMUxKU0Zpd1JwSlFNZlRQaktabEQxUXdrN3Npd2lqR0d5S0pDOXJHRGo4N3dPWHwzMDc0NDU3MzU2MjI1OTQwOTgz?invite_link_id=122467482007)
- [x] identify problems the refugee will encounter in the journey
- [x] identify and analyze the solutions

**Comment by afinika** [comment]
common questions refugees ask in chats https://docs.google.com/document/d/1bLS6RiDdRmVrvohQH07GXSxPvzZ01WIAot-ESdADSS8/edit?usp=sharing

**Comment by ella-mihaela** [comment]
Problems: brainstorm
https://miro.com/app/board/uXjVOJ8WcAg=/
